### ISSUE TITLE
Sample 01-Login invalid state after login refresh Firefox

### ISSUE THREAD

**Issue by danillouz** [auth0-samples/auth0-react-samples#145]
Hi,

When I run the sample code and refresh the page after a login on Firefox (DE 69.0.0 Mac OS X 10.14.0) I always get an `Error: Invalid state`:

<img width="1460" alt="invalid-state" src="https://user-images.githubusercontent.com/6201287/61619704-aa4c8680-ac6f-11e9-92f8-170cbe795a96.png">

Only when I open a new tab or do a route change, page refreshes work fine. This happens when running locally on `localhost`, but also in an app deployed to a custom domain, that basically shares the same implementation using `@auth0/auth0-spa-js` version `1.0.2`.
This doesn't happen in Chrome or Safari.

I made sure I'm not blocking any cookies nor any critical requests.
And I don't see anything weird in the Auth0 dashboard logs:
- [Success Exchange](https://manage.auth0.com/dashboard/eu/radient/logs/90020190722093040899390780899506055018957569727991382034)
- [Success Silent Auth](https://manage.auth0.com/dashboard/eu/radient/logs/90020190722093040771408095040386371362815721370975993874)

I tried to get a better understanding why this might be happening by digging through the code of `@auth0/auth0-spa-js`, where I see a token is requested silently when initializing the lib with `createAuth0Client`. This runs on page refresh, but my understanding is that [`prompt: 'none'`](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L318) shouldn't be triggering a redirect flow with a new `code`, which appears to be happening.
Could it be that the request fails to run in the iframe the first time after login for some reason in Firefox only?

If you can reproduce the error, I'm happy to help investigating if needed.

**Comment by luisrudge** [comment]
This is happening because the page is not being redirected after the callback is done (you still have the `?code=` in your URL, so the react wrapper [will try to handle the callback again](https://github.com/auth0-samples/auth0-react-samples/blob/master/01-Login/src/react-auth0-spa.js#L26) which will trigger a state error. Can you check why your code is not reaching this line? https://github.com/auth0-samples/auth0-react-samples/blob/master/01-Login/src/index.js#L10

**Comment by danillouz** [comment]
Hi @luisrudge thank you for your reply, but I don't think that's it.
The code you mention is being executed. When I add some `console.log` statements I see them printed.

Code:
```js
const onRedirectCallback = appState => {
  console.log('onRedirectCallback()');

  window.history.replaceState(
    {},
    document.title,
    appState && appState.targetUrl
      ? appState.targetUrl
      : window.location.pathname
  );

  console.log('called window.history.replaceState()');
};
```

This is the flow:

1. Run the application locally and click on login:
<img width="1460" alt="01" src="https://user-images.githubusercontent.com/6201287/61690534-d62c4280-ad29-11e9-8ba3-d434c2874288.png">

2. I get redirected to the login screen and fill in my credentials:
<img width="1463" alt="02" src="https://user-images.githubusercontent.com/6201287/61690559-e9d7a900-ad29-11e9-9e32-36e29757840a.png">

3. I get redirected back to the app, and I see the `?code=&state=` params in the URL.

4. `onRedirectCallback` is called and removes the URL params (notice the logs in the web console and the URL is now `localhost:3000`). I'm now logged in. All is well:
<img width="1461" alt="04" src="https://user-images.githubusercontent.com/6201287/61690703-37541600-ad2a-11e9-85ab-462bf08495e1.png">

5. If at this stage the first thing I do is refresh the page, I get `Error: Invalid state` (this only happens in Firefox). Where it seems a new redirect is happening with new `code` and `state` params present in the URL:
<img width="1461" alt="05" src="https://user-images.githubusercontent.com/6201287/61690768-610d3d00-ad2a-11e9-8a64-48e46f0fd94d.png">

If however after step 4 I change the route first, by for example navigating to the `/profile` page or just open a new tab (I'm still logged in) and then do a page refresh, I do _not_ get `Error: Invalid state` (step) 5 and everything works fine.

**Comment by luisrudge** [comment]
Ahhh, yeah. We've (seen)[https://github.com/auth0/auth0.js/issues/655#issuecomment-451939029] this happening with our samples before. For some reason, Firefox uses the previous page when you do a manual refresh, which will cause this issue.

**Comment by danillouz** [comment]
Oh wow, this seems to be a bug withing Firefox itself then. After going through the issue, I now see the URL at step 5 is exactly the same as in step 3 (same `code` and `state`). At first I thought this was a new redirect.

**Comment by luisrudge** [comment]
Sorry I didn't make it more clear, but yeah. It's like Firefox is using the url BEFORE the `pushState`.

**Comment by danillouz** [comment]
Yup, it is a bug in Firefox, which was reported 2 years ago 🤣
https://bugzilla.mozilla.org/show_bug.cgi?id=1422334

It seems to happen in combination with redirects and that Firefox is trying to reload from cache.
Someone suggested using this as a workaround:
```js
location.hash = location.hash;
```

I just tested this in the sample like so:
```js
const onRedirectCallback = appState => {
  // Firefox workaround
  window.location.hash = window.location.hash;

  window.history.replaceState(
    {},
    document.title,
    appState && appState.targetUrl
      ? appState.targetUrl
      : window.location.pathname
  );
};
```

And this actually makes it work as expected.

Do you think it would be a good idea to update the code sample with this and add some documentation to the README and code? I'm happy to send a PR.

**Comment by luisrudge** [comment]
@danillouz your googling skills are amazing. I swear a looked everywhere for a bug like this 😬 Although, I was dumb enough to search for `pushState` instead of `replaceState` 😭.

Thanks so much for helping with this! 🎉 

Do you think that would be a good addition to our (FAQ)[https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md]?

**Comment by danillouz** [comment]
@luisrudge haha I guess I have a lot of experience googling errors 😅

You're welcome, I'm glad to help! 💯💪

Yes, the FAQ makes sense. Shall I also comment the link in the code to the FAQ, or just mention details can be found in the FAQ?

**Comment by luisrudge** [comment]
I think just adding this to the FAQ is enough. We can't possibly put all browser bugs in our quickstarts, but we can mention the ones that affect the user the most in our FAQ. What do you think?

**Comment by danillouz** [comment]
Yes, I think you're right. Adding it to all sample code would add quite some extra maintenance. Since this should only be a temporary workaround, which should be removed after the issue is fixed in Firefox.

I'll just do one more test with the app I have deployed to a custom domain and then I'll send a PR in the `auth0-spa-js` repo.

**Comment by yellowtailfan** [comment]
The Firefox bug has been resolved:

https://bugzilla.mozilla.org/show_bug.cgi?id=1422334

Has it been verified that this Auth0 behaviour is fixed with new versions of Firefox? Should the FAQ be updated?

**Comment by stevehobbsdev** [comment]
Thanks @yellowtailfan, let me verify and update the FAQ if necessary 👍🏻

**Comment by swrobel** [comment]
@stevehobbsdev I still see this [in the FAQ](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-do-i-get-error-invalid-state-in-firefox-when-refreshing-the-page-immediately-after-a-login). Wasn't it resolved in Firefox 70 (about 22 FFx versions ago based on the current 92.0)
